version: '3.8'

services:
  redis:
    image: 'redis:7.2'
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - user_management_network

volumes:
  redis_data:

networks:
  user_management_network:
    external: true
